# -*- coding: utf-8 -*-
"""processing_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHXJJ1KDSVBzKCmurpwRvJZOrrn5cQmQ
"""

import pandas as pd
import numpy as np
from scipy.stats import zscore

# Load data
file_path = "/content/StudentsPerformance.csv"
df = pd.read_csv(file_path)

# Handle missing values
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())


# Encode categorical values
if 'gender' in df.columns:
    df['gender'] = df['gender'].map({'male': 0, 'female': 1})


# Remove outliers using Z-score method
numerical_cols = ['math score', 'reading score', 'writing score']
df = df[(np.abs(zscore(df[numerical_cols])) < 3).all(axis=1)]

# Save processed data
df.to_csv("processed_datafile.csv", index=False)
print("Preprocessing complete. Cleaned data saved.")