# -*- coding: utf-8 -*-
"""analyze_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10IVeFknSUAVboSfPnQYJLcOIDLjrAkju
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load processed data
df = pd.read_csv("processed_frailty_data.csv")

# 1Summary Statistics
summary = df.describe()
summary.to_csv("results/summary_stats.txt")
print(summary)

# Correlation Check (Grip Strength vs Frailty)
correlation = df["Grip strength "].corr(df["Frailty"])
print(f"Correlation between Grip Strength and Frailty: {correlation:.3f}")

# Visualization: Boxplot of Grip Strength by Frailty
sns.boxplot(x=df["Frailty"], y=df["Grip strength "])
plt.xlabel("Frailty (0 = No, 1 = Yes)")
plt.ylabel("Grip Strength (kg)")
plt.title("Grip Strength vs. Frailty")
plt.savefig("results/plots/grip_vs_frailty.png")
plt.show()