# -*- coding: utf-8 -*-
"""clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UYvoLpQuFh7HvNagTpVq5cefu9oPNO9X
"""

import pandas as pd
import os

# Define file paths
input_file = "/content/raw_frailty_data.csv"
output_file = "/content/processed/processed_frailty_data.csv"

# Ensure output directory exists
os.makedirs("processed", exist_ok=True)

# Load raw data
df = pd.read_csv(input_file)

# Convert 'Frailty' column from categorical ('Y'/'N') to numerical (1/0)
df["Frailty"] = df["Frailty"].map({"N": 0, "Y": 1})

# Save cleaned data
df.to_csv(output_file, index=False)

print(f"Processed data saved to {output_file}")